repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=79", "--exclude=.git,__pycache__,venv/"]

  - repo: local
    hooks:
      - id: commit-msg-check
        name: Commit Message Check
        entry: scripts/commit-msg-check.sh
        language: script
        stages: [commit-msg]