- name: Install application dependencies
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - pkg-config
          - libmysqlclient-dev
          - default-libmysqlclient-dev
          - build-essential
          - python3-venv
        state: present
        update_cache: true
